version: '3'

services:
  api:
    build: .
    container_name: api
    command: npm start
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  api-dev:
    build: .
    container_name: api-dev
    command: npm run dev
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}

  test:
    build: .
    command: npm run test
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    tty: true
