version: '3'

services:
  api:
    build: .
    container_name: 01card-challenge
    command: npm start
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
